<?php

namespace Extended\ProjectBundle\Repository;

/**
 * ProjectFileGDTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectFileGDTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
